version: "3"

services:
  PingService:
    build: PingService/
    command: python ./main.py
    ports:
      - "8080:8080"

  ReceiverService:
    build: ReceiverService/
    command: python ./main.py
    ports:
      - "8080"

